apiVersion: v1
kind: ConfigMap
metadata:
  name: lemonade-stand-auxiliary-config
  labels:
    app: lemonade-stand
data:
  regexDetectorImage: {{ .Values.regexDetectorImage | quote }}
  vllmGatewayImage: {{ .Values.vllmGatewayImage | quote }}
