#!/usr/bin/env bash
# Generated by quickpat compose -- do not edit
# Creates Kubernetes secrets for lemonade-stand.
# Run before helm install if not using values.yaml secrets.

set -euo pipefail
NAMESPACE="${NAMESPACE:-lemonade-stand}"

echo "Creating secrets for namespace: $NAMESPACE"

# Secret: llm-vllm-api-key
read -rsp "Enter vllm-api-key for llm-vllm-api-key: " VLLM_API_KEY; echo
oc create secret generic llm-vllm-api-key \
  --from-literal=vllm-api-key="${VLLM_API_KEY}"
  -n "$NAMESPACE" --dry-run=client -o yaml | oc apply -f -

# Secret: model-storage-access-key
read -rsp "Enter AWS_ACCESS_KEY_ID for model-storage-access-key: " AWS_ACCESS_KEY_ID; echo
oc create secret generic model-storage-access-key \
  --from-literal=AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
  -n "$NAMESPACE" --dry-run=client -o yaml | oc apply -f -

# Secret: model-storage-secret-key
read -rsp "Enter AWS_SECRET_ACCESS_KEY for model-storage-secret-key: " AWS_SECRET_ACCESS_KEY; echo
oc create secret generic model-storage-secret-key \
  --from-literal=AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
  -n "$NAMESPACE" --dry-run=client -o yaml | oc apply -f -

echo "Secrets created successfully."
echo "You can now run: helm install lemonade-stand ./chart -n $NAMESPACE"
