apiVersion: apps/v1
kind: Deployment
metadata:
  name: lingua-detector
  labels:
    app: lingua-detector
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: lingua-detector
  template:
    metadata:
      labels:
        app: lingua-detector
    spec:
      containers:
        - name: lingua-detector
          image: {{ .Values.image }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory }}
